language: python
python:
  - 3.5.2

install:
  - pip install -r requirements.txt
  - export PYTHONPATH=$(pwd)/src/
  - pip install coveralls

script:
  - coverage run -m --branch --source=src --omit=src/tests/* unittest discover -s src/tests

after_success:
  - coveralls



