language: python
python:
  - 3.5.2

install:
  - pip install -r requirements.txt
  - pip install coverage
  -

script:
  - coverage run -m --branch --source=src --omit=src/tests/* unittest discover -s src/tests



